name: Release (macOS)

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install frontend deps
        run: npm ci

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Rust
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            src-tauri

      - name: Install Tauri CLI
        run: npm i -D @tauri-apps/cli

      - name: Build frontend
        run: npm run build

      - name: Build Tauri app (DMG)
        env:
          # Provide Apple signing env if you want to notarize/sign
          # TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          # TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
          # APPLE_ID: ${{ secrets.APPLE_ID }}
          # APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
          # APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          CI: true
        run: npx tauri build --bundles dmg

      - name: Upload DMG artifact
        uses: actions/upload-artifact@v4
        with:
          name: banshee-macos-dmg
          path: src-tauri/target/release/bundle/dmg/*.dmg
